//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_MANGE_COURCE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int schedule_id { get; set; }
        public Nullable<int> teacher_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> class_id { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date_week { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
